### ISSUE TITLE
Second Terminology Window is Unresponsive

### ISSUE THREAD

**Issue by cyniphile** [billiob/terminology#50]
When I open a second or third terminology window, sometimes the new window displays only an unresponsive window frame. Happy post some logs or other relevant data to help debug, but not sure what would be helpful. 

Running Terminology 0.9.1 on Ubuntu 16.04, but the issue also happened before I upgraded from 14.04 as well. 

![image](https://cloud.githubusercontent.com/assets/1314176/15825547/33c747f0-2bd2-11e6-8480-45f451621089.png)

**Comment by billiob** [comment]
Could you open the bug report on  https://phab.enlightenment.org/maniphest/task/create/ ?
There, can you answer whether you are running terminology with the option (in behavior) called "Multiple instances, one process" ?
Do you have the same issue if you start terminology from an other terminal (in order to get possible logs) ?

**Comment by cyniphile** [comment]
@billiob I'll do that.

FYI, I enabled "Multiple Instances, one process" in settings/behavior and the problem does not occur.
